server:
  port: 8081

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    properties.hibernate.jdbc.lob.non_contexual_creation: true

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: hooman
    password: password
  sql:
    init:
      platform: postgres
      mode: always

