version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hooman
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql/data